version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - cd frontend
      - npm install
  
  build:
    commands:
      - echo Build started on `date`
      - echo Building React application...
      - npm run build
  
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading to S3...
      - aws s3 sync dist/ s3://$S3_BUCKET/ --delete
      - echo Creating CloudFront invalidation...
      - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_ID --paths "/*"

artifacts:
  files:
    - 'frontend/dist/**/*'
  base-directory: frontend
